config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'home/index'
  resources :posts
  resources :categories
  root to: "home#index"

  get '/about', :to => 'pages#about'
  get '/resources', :to => 'pages#resources'
  get '/contact', :to => 'pages#contact'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	attr_accessor :name
	has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
	attr_accessor :title, :body, :category_id,  :author_id
	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery unless: -> { request.format.json? }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @title = @category.name
    @posts = @category.posts
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def resources
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
	  @posts = Post.all
  end
 
  def show
	  @post = Post.find(params[:id])
  end

  def new 
    @post = Post.new
	@category = Category.all
  end

  def create
    @post = Post.new(post_params)
	if @post.save
	      redirect_to posts_path, :notice => "Your Post has been saved"
	else
	  render "new"
	end
		  
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(post_params)
	    redirect_to post_path, :notice => "Your Post has been updated"
    else
      render "edit"
    end      
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, :notice => "Your Post has been deleted"
  end

  private def post_params
  params.require(:post).permit!
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/index.html.erb
<h2>Categories</h2>
<% @categories.each do |category| %>
<p><%= link_to category.name,category %></p>
</hr>
<% end %>

app/views/categories/show.html.erb
<% @posts.each do |post| %>
<h3> <%= link_to post.title.post %></h3>
<p><%= post.body %></p>
<% end %> 

app/views/home/index.html.erb
<h1>This is my Home page! Welocme to ruby on Rails !!</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyRubyonRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div>
    <ul class="main-nav">
	  <li><%= link_to "Home", root_path %></li>	
	  <li><%= link_to "Blog", posts_path %></li>
	  <li><%= link_to "About", about_path %></li>
	  <li><%= link_to "Contact", contact_path %></li>
	  <li><%= link_to "Resource", resources_path %></li>
    </ul>
  </div>

    <% flash.each do |key, value| %>
	    <p><%= value %></p>
    <% end %>	    

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<h1>Company Overview</h1>
<h3>Technology solutions to help businesses and societies flourish</h3>
<h4>
Mindtree delivers digital transformation and technology services from ideation to execution, enabling Global 2000 clients to outperform the competition. “Born digital,” Mindtree takes an agile, collaborative approach to creating customized solutions across the digital value chain. Our deep expertise in infrastructure and applications management turns IT into a strategic asset. Whether you need to run your business more efficiently or accelerate revenue growth, Mindtree can get you there.</h4>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/resources.html.erb
<h1>Pages#resources</h1>
<p>Find me in app/views/pages/resources.html.erb</p>

app/views/posts/create.html.erb
<h1>This is Index page for  Posts !!</h1>
<h3>This First Sample Blog</h3>
<p>This is sample text for sample bolg 1</p>
<p>Find me in app/views/home/index.html.erb</p>

app/views/posts/destroy.html.erb
<h1>This is Index page for  Posts !!</h1>
<h3>This First Sample Blog</h3>
<p>This is sample text for sample bolg 1</p>
<p>Find me in app/views/home/index.html.erb</p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for @post do |f| %>
<p>
<%= f.label :title %></br>
<%= f.text_field :title %></br>
</p>
<p>
<%= f.label :body %></br>
<%= f.text_area :body %></br>
</p>
<p><%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => "Select One"} %></br>
</p>
<p>
<%= f.submit "Edit Post" %></br>
</p>
<% end %>
<%= link_to "Go Back",post_path %>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<% @posts.each do |post| %>
<h3><%= link_to post.title,post %></h3>
<p><%= post.body %></p>
</hr>
<% end %>
<%= link_to "Add New Post", new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_for @post do |f| %>
<p>
<%= f.label :title %></br>
<%= f.text_field :title %></br>
</p>
<p>
<%= f.label :body %></br>
<%= f.text_area :body %></br>
</p>
<p><%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => "Select One"} %></br>
</p>
<p>
<%= f.submit "New Post" %></br>
</p>
<% end %>

app/views/posts/show.html.erb
<h1>Blog Post</h1>
<h3><%= @post.title %></h3>
<small><%= @post.created_at.strftime("%b %d. %Y") %></small>
<p><%= @post.body %></p>
<p> Category: <%=  @post.category.name %></p>
<%= link_to "Edit Post", edit_post_path %> | <%= link_to "Delete", @post, :confirm => "Are you sure want to delete the post ?", :method => :delete %>
<%= link_to "Back", posts_path %> 

app/views/posts/update.html.erb
<h1>This is Index page for  Posts !!</h1>
<h3>This First Sample Blog</h3>
<p>This is sample text for sample bolg 1</p>
<p>Find me in app/views/home/index.html.erb</p>